name: Build and Test Client Application
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Change to Client directory
        run: cd client

      - name: Install modules
        run: npm ci
        working-directory: ./client

      - name: Run tests
        run: npm run test
        working-directory: ./client

      - name: Run test coverage
        run: npm run test:coverage
        working-directory: ./client

      - name: Check test coverage
        run: npx nyc check-coverage --lines 75 --functions 75 --branches 75
        working-directory: ./client
