name: Build and Test Client Application
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Change to Client directory
        run: cd client

      - name: Install modules
        run: npm ci
        working-directory: ./client

      - name: Run tests
        run: npm run test
        working-directory: ./client

      - name: Report coverage
        # Set if: always() to also generate the report if tests are failing
        # Only works if you set `reportOnFailure: true` in your vite config as specified above
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
