name: Run Tests in Backend

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version}}

      - name: Clean install dependencies
        run: npm ci
        working-directory: ./backend_v1

      - name: Run tests
        env:
          OPEN_API_KEY: ${{ secrets.OPEN_API_KEY }}
          DATABASE_URL_TEST: ${{ secrets.DATABASE_URL_TEST }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
        run: npm test
        working-directory: ./backend_v1
